#include "dialogue_macros.h"

/* ROM 0x0806C538 */
DIALOGUE_SCRIPT(0x0806C538, scene_06C538)
  TALK(SPEAKER_CREWMAN, SIDE_RIGHT, EXPR_ALT,
      "All! I REPEAT!! ALL EARTH SHIPS APPROACHING!!")
END_DIALOGUE_SCRIPT()
