#include "dialogue_macros.h"

/* ROM 0x0807724F */
DIALOGUE_SCRIPT(0x0807724F, scene_07724F)
  TALK(SPEAKER_SCARLET, SIDE_RIGHT, EXPR_NEUTRAL,
      "Its loaded and ready!")
  TALK(SPEAKER_RECKER_KRILL, SIDE_LEFT, EXPR_NEUTRAL,
      "FIRE!!")
END_DIALOGUE_SCRIPT()
