#!/usr/bin/env python3
"""Build append-ROM GAX music/voice catalogs from sound/.

Reads:
  sound/music/*.json
  sound/voice/*.json   (each points at a .bin from pack_gax_speech)

Writes:
  src_custom/generated/gax_catalog.c
  src_custom/generated/gax_catalog.h
"""

from __future__ import annotations

import argparse
import json
import re
import struct
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOUND = REPO / "sound"
OUT_DIR = REPO / "src_custom" / "generated"
OUT_H_DIR = REPO / "include"
PACK_SPEECH = REPO / "tools" / "pack_gax_speech.py"
PACK_SONG = REPO / "tools" / "pack_gax_song.py"


def parse_int(s) -> int:
    if isinstance(s, int):
        return s
    return int(str(s), 0)


def collect_music() -> list[dict]:
    items = []
    music_dir = SOUND / "music"
    if not music_dir.is_dir():
        return items
    for path in sorted(music_dir.glob("*.json")):
        meta = json.loads(path.read_text())
        meta["_path"] = path
        items.append(meta)
    items.sort(key=lambda m: parse_int(m.get("id", 0)))
    return items


def voice_audio_path(meta: dict, json_path: Path) -> Path:
    """Resolve source audio: prefer `src`, then `mp3`, then `wav`."""
    for key in ("src", "mp3", "wav"):
        if key in meta and meta[key]:
            return json_path.parent / meta[key]
    raise KeyError(f"{json_path}: need src, mp3, or wav")


def collect_voice() -> list[dict]:
    items = []
    voice_dir = SOUND / "voice"
    if not voice_dir.is_dir():
        return items
    for path in sorted(voice_dir.glob("*.json")):
        meta = json.loads(path.read_text())
        meta["_path"] = path
        audio = voice_audio_path(meta, path)
        if not audio.is_file():
            raise FileNotFoundError(f"{path}: missing audio {audio}")
        stem = path.parent / "built" / path.stem
        stem.parent.mkdir(parents=True, exist_ok=True)
        subprocess.check_call(
            [sys.executable, str(PACK_SPEECH), str(audio), "-o", str(stem)]
        )
        entry = json.loads(stem.with_suffix(".entry.json").read_text())
        bin_path = stem.with_suffix(".bin")
        meta["_bin"] = bin_path
        meta["_entry"] = entry
        items.append(meta)
    items.sort(key=lambda m: parse_int(m.get("id", 0)))
    return items


def c_ident(name: str) -> str:
    s = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def emit(music: list[dict], voice: list[dict], out_c: Path, out_h: Path) -> None:
    out_c.parent.mkdir(parents=True, exist_ok=True)
    lines_h = [
        "#ifndef GUARD_GAX_CATALOG_H",
        "#define GUARD_GAX_CATALOG_H",
        "",
        "#include \"gba/types.h\"",
        "#include \"gax.h\"",
        "",
        f"#define GAX_MUSIC_COUNT {len(music)}",
        f"#define GAX_VOICE_COUNT {len(voice)}",
        "",
    ]
    for m in music:
        lines_h.append(f"#define GAX_MUSIC_{c_ident(m.get('name', str(m.get('id')))).upper()} {parse_int(m.get('id', 0))}")
    for v in voice:
        lines_h.append(f"#define GAX_VOICE_{c_ident(v.get('name', str(v.get('id')))).upper()} {parse_int(v.get('id', 0))}")
    lines_h += [
        "",
        "extern const u16 gGaxMusicCount;",
        "extern const u16 gGaxVoiceCount;",
        "extern const void *const gGaxMusicTable[];",
        "extern const GaxSpeechEntry gGaxVoiceTable[];",
        "",
        "#endif /* GUARD_GAX_CATALOG_H */",
        "",
    ]
    out_h.write_text("\n".join(lines_h))

    lines = [
        "/* Auto-generated by tools/build_gax_catalog.py — do not edit. */",
        "#include \"runtime.h\"",
        "#include \"gax_catalog.h\"",
        "",
        f"APPEND_RODATA const u16 gGaxMusicCount = {len(music)};",
        f"APPEND_RODATA const u16 gGaxVoiceCount = {len(voice)};",
        "",
    ]

    # Music: vanilla pointers or packed blobs as APPEND_RODATA
    max_music_id = max((parse_int(m.get("id", 0)) for m in music), default=-1)
    music_slots = [None] * (max_music_id + 1 if max_music_id >= 0 else 0)
    for m in music:
        music_slots[parse_int(m.get("id", 0))] = m

    for m in music:
        mid = parse_int(m.get("id", 0))
        name = c_ident(m.get("name", f"music_{mid}"))
        if m.get("vanilla_module"):
            addr = parse_int(m["vanilla_module"])
            lines.append(f"/* music {mid} {name}: vanilla module */")
            lines.append(f"#define GAX_MUSIC_PTR_{mid} ((const void *)0x{addr:08X})")
        else:
            # pack song
            packed = m["_path"].parent / "built" / f"{m['_path'].stem}.bin"
            packed.parent.mkdir(parents=True, exist_ok=True)
            subprocess.check_call(
                [
                    sys.executable,
                    str(PACK_SONG),
                    str(m["_path"]),
                    "-o",
                    str(packed),
                ]
            )
            if packed.suffix == ".bin" and packed.exists() and packed.stat().st_size > 8:
                data = packed.read_bytes()
                lines.append(f"APPEND_RODATA static const u8 sMusicBlob_{mid}[] = {{")
                for i in range(0, len(data), 16):
                    chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
                    lines.append(f"    {chunk},")
                lines.append("};")
                lines.append(f"#define GAX_MUSIC_PTR_{mid} ((const void *)sMusicBlob_{mid})")
            else:
                # vanilla_module sidecar from packer skip
                side = json.loads(packed.read_text()) if packed.exists() else {}
                addr = parse_int(side.get("vanilla_module", 0x081310F0))
                lines.append(f"#define GAX_MUSIC_PTR_{mid} ((const void *)0x{addr:08X})")

    lines.append("")
    lines.append("APPEND_RODATA const void *const gGaxMusicTable[] = {")
    if not music_slots:
        lines.append("    0,")
    for i, m in enumerate(music_slots):
        if m is None:
            lines.append("    0,")
        else:
            lines.append(f"    GAX_MUSIC_PTR_{parse_int(m.get('id', i))},")
    lines.append("};")
    lines.append("")

    # Voice blobs
    max_voice_id = max((parse_int(v.get("id", 0)) for v in voice), default=-1)
    voice_slots = [None] * (max_voice_id + 1 if max_voice_id >= 0 else 0)
    for v in voice:
        voice_slots[parse_int(v.get("id", 0))] = v

    for v in voice:
        vid = parse_int(v.get("id", 0))
        data = Path(v["_bin"]).read_bytes()
        lines.append(f"APPEND_RODATA static const u8 sVoiceBlob_{vid}[] = {{")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
            lines.append(f"    {chunk},")
        lines.append("};")

    lines.append("")
    lines.append("APPEND_RODATA const GaxSpeechEntry gGaxVoiceTable[] = {")
    if not voice_slots:
        lines.append("    {0, 0},")
    for i, v in enumerate(voice_slots):
        if v is None:
            lines.append("    {0, 0},")
        else:
            vid = parse_int(v.get("id", i))
            sf = v["_entry"]["size_flags"]
            lines.append(f"    {{ sVoiceBlob_{vid}, 0x{sf:08X} }},")
    lines.append("};")
    lines.append("")

    out_c.write_text("\n".join(lines))
    print(f"wrote {out_c} ({len(music)} music, {len(voice)} voice)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-c", type=Path, default=OUT_DIR / "gax_catalog.c")
    ap.add_argument("--out-h", type=Path, default=OUT_H_DIR / "gax_catalog.h")
    args = ap.parse_args()
    music = collect_music()
    voice = collect_voice()
    emit(music, voice, args.out_c, args.out_h)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
