#!/usr/bin/env python3
"""Compile src_custom/data_structures/*.json into APPEND_RODATA C tables.

enemy_exp.json (schema 2): per-enemy catalog → gEnemyExpRemap + gEnemyExpById.
Runtime remaps AddExperience amounts that match an entry's exp (identity unless
you point multiple tiers at new values via shared amounts); by-id is the
per-type catalog.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def load_enemy_exp(path: Path) -> dict:
    data = json.loads(path.read_text())
    schema = data.get("schema")
    if schema not in (1, 2):
        raise ValueError(f"{path}: unsupported schema {schema!r}")
    enemies = data.get("enemies")
    if not isinstance(enemies, list) or not enemies:
        raise ValueError(f"{path}: expected non-empty 'enemies' array")
    return data


def compile_enemy_exp(
    data: dict,
) -> tuple[list[tuple[int, int, str]], list[tuple[int, int, str]]]:
    """Return (remap_rows, by_id_rows)."""
    schema = data["schema"]
    remap: dict[int, tuple[int, str]] = {}
    by_id: dict[int, tuple[int, str]] = {}

    for i, entry in enumerate(data["enemies"]):
        if not isinstance(entry, dict):
            raise ValueError(f"enemies[{i}]: expected object")

        if schema == 1:
            try:
                key = int(entry["vanilla"])
                exp = int(entry["exp"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer vanilla and exp") from exc
            label = str(entry.get("label", f"{key}_exp"))
            eid = None
        else:
            try:
                exp = int(entry["exp"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer exp") from exc
            key = exp
            label = str(entry.get("name") or f"type_{entry.get('id', i)}")
            try:
                eid = int(entry["id"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer id") from exc

        if not 0 <= key <= 0xFFFF or not 0 <= exp <= 0xFFFF:
            raise ValueError(f"enemies[{i}]: values out of u16 range")

        if key not in remap:
            remap[key] = (exp, label)

        if eid is not None:
            if not 0 <= eid <= 0xFFFF:
                raise ValueError(f"enemies[{i}]: id out of u16 range")
            if eid not in by_id:
                by_id[eid] = (exp, label)

    remap_rows = sorted((k, e, lab) for k, (e, lab) in remap.items())
    by_id_rows = sorted((i, e, lab) for i, (e, lab) in by_id.items())
    return remap_rows, by_id_rows


def emit_c(
    remap_rows: list[tuple[int, int, str]],
    by_id_rows: list[tuple[int, int, str]],
) -> str:
    lines = [
        "/* Auto-generated by tools/compile_data_structures.py — do not edit. */",
        "",
        '#include "runtime.h"',
        '#include "data_structures.h"',
        "",
        "APPEND_RODATA const EnemyExpRemapEntry gEnemyExpRemap[] = {",
    ]
    for key, exp, label in remap_rows:
        lines.append(f"    {{ {key}, {exp} }}, /* {label} */")
    if not remap_rows:
        lines.append("    { 0, 0 },")
    lines.append("};")
    lines.append(f"APPEND_RODATA const u16 gEnemyExpRemapCount = {len(remap_rows)};")
    lines.append("")
    lines.append("APPEND_RODATA const EnemyExpIdEntry gEnemyExpById[] = {")
    for eid, exp, label in by_id_rows:
        lines.append(f"    {{ {eid}, {exp} }}, /* {label} */")
    if not by_id_rows:
        lines.append("    { 0, 0 },")
    lines.append("};")
    lines.append(f"APPEND_RODATA const u16 gEnemyExpByIdCount = {len(by_id_rows)};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        default=REPO / "src_custom" / "data_structures",
        help="Directory of JSON data structure files",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output data_structures_tables.c path",
    )
    args = parser.parse_args()

    enemy_path = args.src / "enemy_exp.json"
    if not enemy_path.is_file():
        print(f"error: missing {enemy_path}", file=sys.stderr)
        return 1

    try:
        data = load_enemy_exp(enemy_path)
        remap_rows, by_id_rows = compile_enemy_exp(data)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_c(remap_rows, by_id_rows))
    print(
        f"data_structures: enemy_exp → {len(remap_rows)} remap, "
        f"{len(by_id_rows)} by-id entries"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
