#!/usr/bin/env python3
"""Compile src_custom/data_structures/*.json into APPEND_RODATA C tables.

enemy_exp.json (schema 2): per-enemy catalog → gEnemyExpRemap + gEnemyExpById.
impact_suction.json (schema 1): custom Impact Data → gCustomImpacts.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
IMPACT_DESC_STRIDE = 0x5A


def load_enemy_exp(path: Path) -> dict:
    data = json.loads(path.read_text())
    schema = data.get("schema")
    if schema not in (1, 2):
        raise ValueError(f"{path}: unsupported schema {schema!r}")
    enemies = data.get("enemies")
    if not isinstance(enemies, list) or not enemies:
        raise ValueError(f"{path}: expected non-empty 'enemies' array")
    return data


def compile_enemy_exp(
    data: dict,
) -> tuple[list[tuple[int, int, str]], list[tuple[int, int, str]]]:
    """Return (remap_rows, by_id_rows)."""
    schema = data["schema"]
    remap: dict[int, tuple[int, str]] = {}
    by_id: dict[int, tuple[int, str]] = {}

    for i, entry in enumerate(data["enemies"]):
        if not isinstance(entry, dict):
            raise ValueError(f"enemies[{i}]: expected object")

        if schema == 1:
            try:
                key = int(entry["vanilla"])
                exp = int(entry["exp"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer vanilla and exp") from exc
            label = str(entry.get("label", f"{key}_exp"))
            eid = None
        else:
            try:
                exp = int(entry["exp"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer exp") from exc
            key = exp
            label = str(entry.get("name") or f"type_{entry.get('id', i)}")
            try:
                eid = int(entry["id"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"enemies[{i}]: need integer id") from exc

        if not 0 <= key <= 0xFFFF or not 0 <= exp <= 0xFFFF:
            raise ValueError(f"enemies[{i}]: values out of u16 range")

        if key not in remap:
            remap[key] = (exp, label)

        if eid is not None:
            if not 0 <= eid <= 0xFFFF:
                raise ValueError(f"enemies[{i}]: id out of u16 range")
            if eid not in by_id:
                by_id[eid] = (exp, label)

    remap_rows = sorted((k, e, lab) for k, (e, lab) in remap.items())
    by_id_rows = sorted((i, e, lab) for i, (e, lab) in by_id.items())
    return remap_rows, by_id_rows


def load_custom_impacts(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    if data.get("schema") != 1:
        raise ValueError(f"{path}: unsupported schema {data.get('schema')!r}")
    impacts = data.get("impacts")
    if not isinstance(impacts, list) or not impacts:
        raise ValueError(f"{path}: expected non-empty 'impacts' array")

    rows: list[dict] = []
    for i, entry in enumerate(impacts):
        if not isinstance(entry, dict):
            raise ValueError(f"impacts[{i}]: expected object")
        try:
            index = int(entry["index"])
            gun_id = int(entry["id"])
            number = int(entry["number"])
            icon_from = int(entry["icon_from"])
            name = str(entry["name"]).strip()
            text = str(entry["text"]).strip()
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(
                f"impacts[{i}]: need index, id, number, icon_from, name, text"
            ) from exc

        if not 0 <= index <= 31 or not 0 <= gun_id <= 255:
            raise ValueError(f"impacts[{i}]: index/id out of range")
        if not 0 <= icon_from <= 27:
            raise ValueError(f"impacts[{i}]: icon_from must be a vanilla impact 0..27")
        if not 1 <= number <= 99:
            raise ValueError(f"impacts[{i}]: number out of range")

        desc = f"{name} : {text} "
        if len(desc) >= IMPACT_DESC_STRIDE:
            raise ValueError(
                f"impacts[{i}]: name+text too long for 0x{IMPACT_DESC_STRIDE:X}-byte slot"
            )
        rows.append(
            {
                "index": index,
                "id": gun_id,
                "number": number,
                "icon_from": icon_from,
                "desc": desc,
                "label": name,
            }
        )
    return rows


def c_string_bytes(s: str, size: int) -> str:
    raw = s.encode("ascii") + b"\0"
    if len(raw) > size:
        raise ValueError(f"string too long ({len(raw)} > {size})")
    raw = raw.ljust(size, b"\0")
    return ", ".join(str(b) for b in raw)


def emit_c(
    remap_rows: list[tuple[int, int, str]],
    by_id_rows: list[tuple[int, int, str]],
    impacts: list[dict],
) -> str:
    lines = [
        "/* Auto-generated by tools/compile_data_structures.py — do not edit. */",
        "",
        '#include "runtime.h"',
        '#include "data_structures.h"',
        "",
        "APPEND_RODATA const EnemyExpRemapEntry gEnemyExpRemap[] = {",
    ]
    for key, exp, label in remap_rows:
        lines.append(f"    {{ {key}, {exp} }}, /* {label} */")
    if not remap_rows:
        lines.append("    { 0, 0 },")
    lines.append("};")
    lines.append(f"APPEND_RODATA const u16 gEnemyExpRemapCount = {len(remap_rows)};")
    lines.append("")
    lines.append("APPEND_RODATA const EnemyExpIdEntry gEnemyExpById[] = {")
    for eid, exp, label in by_id_rows:
        lines.append(f"    {{ {eid}, {exp} }}, /* {label} */")
    if not by_id_rows:
        lines.append("    { 0, 0 },")
    lines.append("};")
    lines.append(f"APPEND_RODATA const u16 gEnemyExpByIdCount = {len(by_id_rows)};")
    lines.append("")
    lines.append("APPEND_RODATA const CustomImpactEntry gCustomImpacts[] = {")
    if not impacts:
        lines.append("    { 0, 0, 0, 0, { 0 } },")
    for row in impacts:
        desc_bytes = c_string_bytes(row["desc"], IMPACT_DESC_STRIDE)
        lines.append("    {")
        lines.append(
            f"        {row['index']}, {row['id']}, {row['number']}, {row['icon_from']},"
        )
        lines.append(f"        {{ {desc_bytes} }}")
        lines.append(f"    }}, /* {row['label']} */")
    lines.append("};")
    lines.append(f"APPEND_RODATA const u16 gCustomImpactCount = {len(impacts)};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--src",
        type=Path,
        default=REPO / "src_custom" / "data_structures",
        help="Directory of JSON data structure files",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output data_structures_tables.c path",
    )
    args = parser.parse_args()

    enemy_path = args.src / "enemy_exp.json"
    impact_path = args.src / "impact_suction.json"
    if not enemy_path.is_file():
        print(f"error: missing {enemy_path}", file=sys.stderr)
        return 1
    if not impact_path.is_file():
        print(f"error: missing {impact_path}", file=sys.stderr)
        return 1

    try:
        data = load_enemy_exp(enemy_path)
        remap_rows, by_id_rows = compile_enemy_exp(data)
        impacts = load_custom_impacts(impact_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_c(remap_rows, by_id_rows, impacts))
    print(
        f"data_structures: enemy_exp → {len(remap_rows)} remap, "
        f"{len(by_id_rows)} by-id; custom impacts → {len(impacts)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
